//! Safe, RAII-wrapped bindings around libllama + libmtmd.
//!
//! This mirrors the reference implementation in the Python project's
//! `r2t2_llama/native_ext.cpp`: same call order, same parameters, same
//! tokenizer usage. The point of the port is that results match the Python
//! route byte for byte, so the sequence below is deliberate rather than
//! stylistic.
//!
//! Everything llama.cpp returns is a raw pointer. Each one is owned by a
//! wrapper struct whose `Drop` releases it, so a failure part-way through
//! loading cannot leak.

use std::ffi::{CStr, CString};
use std::path::Path;
use std::ptr::NonNull;

use anyhow::{anyhow, bail, Context as _, Result};

/// Raw bindings generated by bindgen in `build.rs`.
///
/// The generated code is not ours to fix at the source, and this toolchain
/// reports `unnecessary_transmute` inside it. Allowing the lints here keeps
/// `cargo build` clean without touching vendored output.
#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    unnecessary_transmutes,
    clippy::all
)]
pub mod sys {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

// --------------------------------------------------------------------------- //
// RAII wrappers
// --------------------------------------------------------------------------- //
//
// Each wrapper owns one llama.cpp pointer and frees it on drop.
//
// SAFETY (why these are `Send`/`Sync`): the pointers are opaque handle types
// from llama.cpp, not references into Rust data, so moving the wrapper between
// threads is fine as long as calls are not *concurrent*. `Engine::run` takes
// `&self` and mutates the shared context, so `Engine` is `Sync` only in the
// sense that its methods must be externally serialised -- which the server does
// with a mutex. Marking the wrappers `Send` (not `Sync`) keeps the guards
// honest: it permits moving the engine to another thread, while the server's
// mutex is what makes concurrent use safe.

/// `llama_model *` that frees itself.
struct Model(NonNull<sys::llama_model>);

// SAFETY: see the note above on the handle types.
unsafe impl Send for Model {}

impl Drop for Model {
    fn drop(&mut self) {
        unsafe { sys::llama_model_free(self.0.as_ptr()) }
    }
}

/// `llama_context *` that frees itself.
struct Context(NonNull<sys::llama_context>);

// SAFETY: see the note above on the handle types.
unsafe impl Send for Context {}

impl Drop for Context {
    fn drop(&mut self) {
        unsafe { sys::llama_free(self.0.as_ptr()) }
    }
}

/// `mtmd_context *` that frees itself.
struct Mtmd(NonNull<sys::mtmd_context>);

// SAFETY: see the note above on the handle types.
unsafe impl Send for Mtmd {}

impl Drop for Mtmd {
    fn drop(&mut self) {
        unsafe { sys::mtmd_free(self.0.as_ptr()) }
    }
}

/// `mtmd_bitmap *` that frees itself.
struct Bitmap(NonNull<sys::mtmd_bitmap>);

impl Drop for Bitmap {
    fn drop(&mut self) {
        unsafe { sys::mtmd_bitmap_free(self.0.as_ptr()) }
    }
}

/// `mtmd_input_chunks *` that frees itself.
struct InputChunks(NonNull<sys::mtmd_input_chunks>);

impl Drop for InputChunks {
    fn drop(&mut self) {
        unsafe { sys::mtmd_input_chunks_free(self.0.as_ptr()) }
    }
}

/// `llama_sampler *` that frees itself.
struct Sampler(NonNull<sys::llama_sampler>);

impl Drop for Sampler {
    fn drop(&mut self) {
        unsafe { sys::llama_sampler_free(self.0.as_ptr()) }
    }
}

/// Turn a null-check on a raw pointer into a `NonNull`, or a descriptive error.
fn non_null<T>(p: *mut T, what: &str) -> Result<NonNull<T>> {
    NonNull::new(p).ok_or_else(|| anyhow!("{what}"))
}

// --------------------------------------------------------------------------- //
// configuration
// --------------------------------------------------------------------------- //

/// Tunables for the engine, mirroring `LlamaNativeConfig` on the Python side.
#[derive(Debug, Clone)]
pub struct EngineConfig {
    /// Path to the language-model GGUF.
    pub model: String,
    /// Path to the `mmproj` audio-projector GGUF.
    pub mmproj: String,
    pub n_ctx: u32,
    pub n_batch: u32,
    pub n_threads: i32,
    pub use_gpu: bool,
    /// `-1` means "offload every layer".
    pub n_gpu_layers: i32,
}

impl EngineConfig {
    pub fn new(model: impl AsRef<Path>, mmproj: impl AsRef<Path>) -> Self {
        Self {
            model: model.as_ref().to_string_lossy().into_owned(),
            mmproj: mmproj.as_ref().to_string_lossy().into_owned(),
            n_ctx: 8192,
            n_batch: 2048,
            n_threads: 16,
            use_gpu: true,
            n_gpu_layers: -1,
        }
    }
}

// --------------------------------------------------------------------------- //
// engine
// --------------------------------------------------------------------------- //

/// A loaded R2T2 model: language model, context, and audio projector.
pub struct Engine {
    model: Model,
    context: Context,
    mtmd: Mtmd,
    n_batch: i32,
}

/// Result of one transcription.
#[derive(Debug, Clone)]
pub struct TranscribeResult {
    pub text: String,
    pub token_ids: Vec<i32>,
    /// `"stop"` if the model emitted an end-of-generation token, else `"length"`.
    pub finish_reason: &'static str,
}

impl Engine {
    /// Load the model, context, and projector. Mirrors `Qwen3ASRNative`'s
    /// constructor, including the assertion that the projector handles audio.
    pub fn load(cfg: &EngineConfig) -> Result<Self> {
        for (path, what) in [(&cfg.model, "model"), (&cfg.mmproj, "mmproj")] {
            if !Path::new(path).exists() {
                bail!("{what} file not found: {path}");
            }
        }

        let model_path =
            CString::new(cfg.model.as_str()).context("model path contains a NUL byte")?;
        let mmproj_path =
            CString::new(cfg.mmproj.as_str()).context("mmproj path contains a NUL byte")?;

        unsafe {
            // Idempotent; safe to call even if another Engine already did.
            sys::llama_backend_init();

            let mut model_params = sys::llama_model_default_params();
            model_params.n_gpu_layers = cfg.n_gpu_layers;
            let model = Model(non_null(
                sys::llama_model_load_from_file(model_path.as_ptr(), model_params),
                &format!("failed to load llama model: {}", cfg.model),
            )?);

            let mut context_params = sys::llama_context_default_params();
            context_params.n_ctx = cfg.n_ctx;
            context_params.n_batch = cfg.n_batch;
            // The reference clamps ubatch to at most 512.
            context_params.n_ubatch = cfg.n_batch.min(512);
            context_params.n_seq_max = 1;
            context_params.n_threads = cfg.n_threads;
            context_params.n_threads_batch = cfg.n_threads;
            context_params.flash_attn_type = sys::llama_flash_attn_type_LLAMA_FLASH_ATTN_TYPE_ENABLED;
            context_params.offload_kqv = cfg.use_gpu;

            let context = Context(non_null(
                sys::llama_init_from_model(model.0.as_ptr(), context_params),
                "failed to create llama context",
            )?);

            let mut mtmd_params = sys::mtmd_context_params_default();
            mtmd_params.use_gpu = cfg.use_gpu;
            mtmd_params.n_threads = cfg.n_threads;
            mtmd_params.warmup = false;

            let mtmd = Mtmd(non_null(
                sys::mtmd_init_from_file(mmproj_path.as_ptr(), model.0.as_ptr(), mtmd_params),
                &format!("failed to load mtmd projector: {}", cfg.mmproj),
            )?);

            if !sys::mtmd_support_audio(mtmd.0.as_ptr()) {
                bail!("the mtmd projector does not support audio");
            }

            Ok(Self {
                model,
                context,
                mtmd,
                n_batch: cfg.n_batch as i32,
            })
        }
    }

    /// Transcribe mono 16 kHz PCM in one shot.
    ///
    /// `prompt` must be the full chat-templated prompt including the audio
    /// marker; see [`crate::prompt::build`].
    pub fn transcribe(&self, audio: &[f32], prompt: &str, max_tokens: i32) -> Result<TranscribeResult> {
        if audio.is_empty() {
            bail!("audio must be a non-empty slice of f32 samples");
        }
        if max_tokens <= 0 {
            bail!("max_tokens must be positive");
        }
        Ok(self.run(audio, prompt, max_tokens)?.into())
    }

    /// Decode `prompt` + `audio` and return just the generated text.
    ///
    /// This is the entry point the streaming loop uses: same prefill, but the
    /// caller only cares about the newly generated continuation, which it then
    /// stitches onto its own prefix.
    pub fn generate(&self, audio: &[f32], prompt: &str, max_tokens: i32) -> Result<String> {
        if audio.is_empty() {
            bail!("audio must be a non-empty slice of f32 samples");
        }
        if max_tokens <= 0 {
            bail!("max_tokens must be positive");
        }
        Ok(self.run(audio, prompt, max_tokens)?.text)
    }

    /// Tokenize text with the vocabulary embedded in the GGUF model.
    ///
    /// The streaming rollback counts in tokens, so this must be the same
    /// tokenizer the generator uses. `add_special = false` matches the
    /// reference, which encodes an already-formed transcript fragment.
    pub fn tokenize(&self, text: &str, add_special: bool, parse_special: bool) -> Result<Vec<i32>> {
        if text.is_empty() {
            return Ok(Vec::new());
        }
        let c_text = CString::new(text).context("text contains a NUL byte")?;
        let vocab = unsafe { sys::llama_model_get_vocab(self.model.0.as_ptr()) };
        if vocab.is_null() {
            bail!("model has no vocabulary");
        }

        unsafe {
            // Negative return means "buffer too small"; the magnitude is the
            // required token count.
            let needed = sys::llama_tokenize(
                vocab,
                c_text.as_ptr(),
                c_text.as_bytes().len() as i32,
                std::ptr::null_mut(),
                0,
                add_special,
                parse_special,
            );
            if needed == 0 {
                return Ok(Vec::new());
            }
            let mut tokens = vec![0i32; needed.unsigned_abs() as usize];
            let n = sys::llama_tokenize(
                vocab,
                c_text.as_ptr(),
                c_text.as_bytes().len() as i32,
                tokens.as_mut_ptr(),
                tokens.len() as i32,
                add_special,
                parse_special,
            );
            if n < 0 {
                bail!("llama_tokenize failed with code {n}");
            }
            tokens.truncate(n as usize);
            Ok(tokens)
        }
    }

    /// Detokenize a token slice into text, mirroring the reference's per-token
    /// `llama_token_to_piece` loop (see [`detokenize`]).
    pub fn detokenize(&self, tokens: &[i32]) -> Result<String> {
        let vocab = unsafe { sys::llama_model_get_vocab(self.model.0.as_ptr()) };
        if vocab.is_null() {
            bail!("model has no vocabulary");
        }
        unsafe { detokenize(vocab, tokens) }
    }

    /// Shared prefill-then-generate path used by both one-shot and streaming.
    fn run(&self, audio: &[f32], prompt: &str, max_tokens: i32) -> Result<TranscribeResult> {

        unsafe {
            // Start from a clean KV cache: this call replaces the whole prompt.
            sys::llama_memory_clear(sys::llama_get_memory(self.context.0.as_ptr()), true);

            // mtmd consumes its own media marker. The vLLM-side prompt uses the
            // Qwen3-ASR triplet, so swap it for mtmd's marker before tokenizing.
            let marker = {
                let raw = sys::mtmd_default_marker();
                if raw.is_null() {
                    bail!("mtmd_default_marker returned null");
                }
                CStr::from_ptr(raw).to_string_lossy().into_owned()
            };
            let mtmd_prompt =
                prompt.replace("<|audio_start|><|audio_pad|><|audio_end|>", &marker);
            if !mtmd_prompt.contains(&marker) {
                bail!("prompt must contain one Qwen3-ASR audio marker");
            }
            let mtmd_prompt_c = CString::new(mtmd_prompt).context("prompt contains a NUL byte")?;

            let bitmap = Bitmap(non_null(
                sys::mtmd_bitmap_init_from_audio(audio.len(), audio.as_ptr()),
                "failed to create mtmd audio bitmap",
            )?);

            let text = sys::mtmd_input_text {
                text: mtmd_prompt_c.as_ptr(),
                text_len: mtmd_prompt_c.as_bytes().len(),
                add_special: true,
                parse_special: true,
            };
            let bitmaps: [*const sys::mtmd_bitmap; 1] = [bitmap.0.as_ptr()];
            let chunks = InputChunks(non_null(
                sys::mtmd_input_chunks_init(),
                "failed to allocate mtmd input chunks",
            )?);

            let rc = sys::mtmd_tokenize(
                self.mtmd.0.as_ptr(),
                chunks.0.as_ptr(),
                &text,
                bitmaps.as_ptr(),
                bitmaps.len(),
            );
            if rc != 0 {
                bail!("mtmd_tokenize failed with code {rc}");
            }

            // Walk the tokenized chunks in order, evaluating each one. Audio
            // chunks are encoded first, then decoded into the KV cache; text
            // chunks go straight through the helper.
            let mut n_past: sys::llama_pos = 0;
            let n_chunks = sys::mtmd_input_chunks_size(chunks.0.as_ptr());

            for i in 0..n_chunks {
                let chunk = sys::mtmd_input_chunks_get(chunks.0.as_ptr(), i);
                if chunk.is_null() {
                    bail!("mtmd_input_chunks_get returned null for chunk {i}");
                }
                let is_last = i + 1 == n_chunks;
                let mut new_n_past: sys::llama_pos = n_past;

                let rc = if sys::mtmd_input_chunk_get_type(chunk)
                    == sys::mtmd_input_chunk_type_MTMD_INPUT_CHUNK_TYPE_TEXT
                {
                    sys::mtmd_helper_eval_chunk_single(
                        self.mtmd.0.as_ptr(),
                        self.context.0.as_ptr(),
                        chunk,
                        n_past,
                        0,
                        self.n_batch,
                        is_last,
                        &mut new_n_past,
                    )
                } else {
                    let encoded = sys::mtmd_encode_chunk(self.mtmd.0.as_ptr(), chunk);
                    if encoded != 0 {
                        encoded
                    } else {
                        let embd = sys::mtmd_get_output_embd(self.mtmd.0.as_ptr());
                        if embd.is_null() {
                            bail!("mtmd returned no audio embedding");
                        }
                        sys::mtmd_helper_decode_image_chunk(
                            self.mtmd.0.as_ptr(),
                            self.context.0.as_ptr(),
                            chunk,
                            embd,
                            n_past,
                            0,
                            self.n_batch,
                            &mut new_n_past,
                            None,
                            std::ptr::null_mut(),
                        )
                    }
                };

                if rc != 0 {
                    bail!("failed to evaluate mtmd chunk {i}, code {rc}");
                }
                n_past = new_n_past;
            }

            // Greedy decoding, stopping at the first end-of-generation token.
            let sampler = Sampler(non_null(
                sys::llama_sampler_init_greedy(),
                "failed to create greedy sampler",
            )?);
            let vocab = sys::llama_model_get_vocab(self.model.0.as_ptr());
            if vocab.is_null() {
                bail!("model has no vocabulary");
            }

            let mut generated: Vec<i32> = Vec::with_capacity(max_tokens as usize);
            let mut finish_reason = "length";

            for _ in 0..max_tokens {
                let token =
                    sys::llama_sampler_sample(sampler.0.as_ptr(), self.context.0.as_ptr(), -1);
                generated.push(token);
                sys::llama_sampler_accept(sampler.0.as_ptr(), token);

                if sys::llama_vocab_is_eog(vocab, token) {
                    finish_reason = "stop";
                    break;
                }

                // Feed the token back in to advance the sequence. Position
                // tracking is implicit here: llama.cpp advances the context
                // itself, and `n_past` is only used by the prefill loop above.
                let mut next_token = token;
                let batch = sys::llama_batch_get_one(&mut next_token, 1);
                if sys::llama_decode(self.context.0.as_ptr(), batch) != 0 {
                    bail!("llama_decode failed during generation");
                }
            }

            // The reference collects the EOG token too (it is pushed before the
            // `is_eog` break), then renders only the non-special pieces. Drop it
            // here so the transcript matches without a trailing `<|im_end|>`.
            let text = detokenize(
                vocab,
                &generated,
            )?;
            let text = strip_trailing_control_tokens(&text);
            Ok(TranscribeResult {
                text,
                token_ids: generated,
                finish_reason,
            })
        }
    }
}

/// Remove trailing special-token text such as `<|im_end|>`.
///
/// `llama_token_to_piece` is called with `special = false`, which suppresses
/// most control tokens but still renders some of them as literal text. The
/// Python route never surfaces these because it stops at the EOG token; this
/// keeps the two transcripts byte-identical.
fn strip_trailing_control_tokens(text: &str) -> String {
    const CONTROLS: [&str; 4] = ["<|im_end|>", "<|endoftext|>", "<|im_start|>", "<asr_text>"];
    let mut s = text.trim_end();
    loop {
        let before = s.len();
        for token in CONTROLS {
            if let Some(stripped) = s.strip_suffix(token) {
                s = stripped.trim_end();
            }
        }
        if s.len() == before {
            return s.to_string();
        }
    }
}

/// Detokenize a token sequence, mirroring `Qwen3ASRNative::detokenize`.
///
/// The reference decodes **one token at a time** with `llama_token_to_piece`
/// (`special = false`), appending each piece. It deliberately does not use
/// `llama_detokenize`, because that would decode the trailing end-of-generation
/// token into visible text such as `<|im_end|>`. Pairing this with the
/// `is_eog` check in the generation loop -- which stops before pushing a
/// further token -- reproduces the Python transcript exactly.
unsafe fn detokenize(vocab: *const sys::llama_vocab, tokens: &[i32]) -> Result<String> {
    let mut out: Vec<u8> = Vec::with_capacity(tokens.len() * 8);
    // 512 bytes is comfortably larger than any single piece this vocab emits.
    let mut buf = [0i8; 512];

    for &token in tokens {
        let n = unsafe {
            sys::llama_token_to_piece(
                vocab,
                token,
                buf.as_mut_ptr(),
                buf.len() as i32,
                0,
                false,
            )
        };
        if n < 0 {
            // Buffer was too small; the API reports the needed size as -n.
            let mut bigger = vec![0i8; (-n) as usize];
            let n2 = unsafe {
                sys::llama_token_to_piece(
                    vocab,
                    token,
                    bigger.as_mut_ptr(),
                    bigger.len() as i32,
                    0,
                    false,
                )
            };
            if n2 > 0 {
                let bytes =
                    unsafe { std::slice::from_raw_parts(bigger.as_ptr() as *const u8, n2 as usize) };
                out.extend_from_slice(bytes);
            }
        } else if n > 0 {
            let bytes = unsafe { std::slice::from_raw_parts(buf.as_ptr() as *const u8, n as usize) };
            out.extend_from_slice(bytes);
        }
    }

    Ok(String::from_utf8_lossy(&out).into_owned())
}
